-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib
import ProcInt.Logs.Trace

/-! # ProcInt.Logs.EventLog

Event logs as lists of traces, with the well-formedness law (every trace timestamp-monotone) and event counting. Port of wasm4pm-compat/src/eventlog.rs::EventLog (traces, event_count, validate); cf. van der Aalst (2016), Def. 4.3. -/

namespace ProcInt

/-- An event log: a finite collection (list) of traces.
Port of `wasm4pm-compat/src/eventlog.rs::EventLog` (traces);
cf. van der Aalst (2016), Def. 4.3. -/
abbrev EventLog (α : Type) := List (Trace α)


/-- A log is well-formed when every trace is timestamp-monotone: the log-level
validation law of `wasm4pm-compat/src/eventlog.rs::EventLog::validate`. -/
def EventLog.wellFormed {α : Type} (log : EventLog α) : Prop :=
  ∀ t ∈ log, Trace.Monotone t


/-- The total number of events in a log, summed over traces. Port of
`EventLog::event_count` in `wasm4pm-compat/src/eventlog.rs`. -/
def EventLog.eventCount {α : Type} (log : EventLog α) : ℕ :=
  (log.map fun t => t.events.length).sum


/-- The empty log is (vacuously) well-formed. -/
theorem EventLog.wellFormed_nil {α : Type} :
    EventLog.wellFormed ([] : EventLog α) := by
  intro t ht
  cases ht


/-- Cons law: a log with one more trace is well-formed iff the new trace is
monotone and the rest of the log is well-formed. -/
theorem EventLog.wellFormed_cons {α : Type} (t : Trace α) (log : EventLog α) :
    EventLog.wellFormed (t :: log) ↔ Trace.Monotone t ∧ EventLog.wellFormed log := by
  simp [EventLog.wellFormed]


/-- Union (append) law: merging two logs preserves and reflects
well-formedness — validation distributes over log union. -/
theorem EventLog.wellFormed_append {α : Type} (l₁ l₂ : EventLog α) :
    EventLog.wellFormed (l₁ ++ l₂) ↔
      EventLog.wellFormed l₁ ∧ EventLog.wellFormed l₂ := by
  simp [EventLog.wellFormed, List.mem_append, or_imp, forall_and]


/-- The empty log contains no events. -/
theorem EventLog.eventCount_nil {α : Type} :
    EventLog.eventCount ([] : EventLog α) = 0 := rfl


/-- Event counting is additive over log union. -/
theorem EventLog.eventCount_append {α : Type} (l₁ l₂ : EventLog α) :
    EventLog.eventCount (l₁ ++ l₂) = EventLog.eventCount l₁ + EventLog.eventCount l₂ := by
  simp [EventLog.eventCount]


/-- Cons law for event counting: adding a trace adds its event count. -/
theorem EventLog.eventCount_cons {α : Type} (t : Trace α) (log : EventLog α) :
    EventLog.eventCount (t :: log) = t.events.length + EventLog.eventCount log := by
  simp [EventLog.eventCount]


/-- Well-formedness is inherited by sublogs: filtering a valid log (as in
`EventLog::filter` views of `wasm4pm-compat/src/eventlog.rs`) never breaks
validation. -/
theorem EventLog.wellFormed_sublist {α : Type} {l₁ l₂ : EventLog α}
    (h : EventLog.wellFormed l₂) (hs : l₁.Sublist l₂) :
    EventLog.wellFormed l₁ :=
  fun t ht => h t (hs.subset ht)


/-- A log has zero events iff every one of its traces is empty — the
degenerate-log characterization behind `EventLog::event_count` in
`wasm4pm-compat/src/eventlog.rs`. -/
theorem EventLog.eventCount_eq_zero {α : Type} (log : EventLog α) :
    EventLog.eventCount log = 0 ↔ ∀ t ∈ log, t.events = [] := by
  simp [EventLog.eventCount, List.sum_eq_zero_iff]



end ProcInt
