-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib

/-! # ProcInt.Logs.Event

Events of a process log: an activity label over an alphabet, a natural-number timestamp, and optional resource/lifecycle annotations. Port of wasm4pm-compat/src/eventlog.rs::Event; cf. van der Aalst, Process Mining: Data Science in Action (2016), Def. 4.1. -/

namespace ProcInt

/-- A single event in a case trace: an activity label over an alphabet `α`, a
natural-number timestamp, and optional resource/lifecycle annotations.
Port of `wasm4pm-compat/src/eventlog.rs::Event` (activity, timestamp_ns,
resource, lifecycle); cf. van der Aalst, Process Mining (2016), Def. 4.1. -/
structure Event (α : Type) where
  activity : α
  timestamp : ℕ
  resource : Option String := none
  lifecycle : Option String := none


/-- The minimal event constructor: activity and timestamp only, no resource or
lifecycle annotation. Mirrors `Event::new(activity).at_ns(t)` in
`wasm4pm-compat/src/eventlog.rs`. -/
def Event.simple {α : Type} (a : α) (t : ℕ) : Event α :=
  ⟨a, t, none, none⟩


/-- `Event.simple` records exactly the given activity. -/
theorem Event.simple_activity {α : Type} (a : α) (t : ℕ) :
    (Event.simple a t).activity = a := rfl


/-- `Event.simple` records exactly the given timestamp. -/
theorem Event.simple_timestamp {α : Type} (a : α) (t : ℕ) :
    (Event.simple a t).timestamp = t := rfl


/-- `Event.simple` carries no resource annotation — the defaulting contract of
`Event::new` in `wasm4pm-compat/src/eventlog.rs`. -/
theorem Event.simple_resource {α : Type} (a : α) (t : ℕ) :
    (Event.simple a t).resource = none := rfl


/-- `Event.simple` carries no lifecycle annotation — the defaulting contract of
`Event::new` in `wasm4pm-compat/src/eventlog.rs`. -/
theorem Event.simple_lifecycle {α : Type} (a : α) (t : ℕ) :
    (Event.simple a t).lifecycle = none := rfl



end ProcInt
