-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib
import ProcInt.Logs.Event

/-! # ProcInt.Logs.Trace

Traces: a case identifier plus its ordered event list, with timestamp monotonicity (List.IsChain of non-decreasing timestamps) and the activity projection. Port of wasm4pm-compat/src/eventlog.rs::Trace and its NonMonotonicTrace validation law; cf. van der Aalst (2016), Def. 4.2. -/

namespace ProcInt

/-- A trace: a case identifier plus the ordered list of its events.
Port of `wasm4pm-compat/src/eventlog.rs::Trace` (case_id, events);
cf. van der Aalst (2016), Def. 4.2 (a trace is a finite sequence of events). -/
structure Trace (α : Type) where
  caseId : String
  events : List (Event α)


/-- Timestamp monotonicity of a trace: adjacent events have non-decreasing
timestamps (`List.IsChain`). This is the `NonMonotonicTrace` validation law of
`wasm4pm-compat/src/eventlog.rs::Trace::validate`. -/
def Trace.Monotone {α : Type} (t : Trace α) : Prop :=
  List.IsChain (fun a b => a.timestamp ≤ b.timestamp) t.events


/-- The activity projection of a trace: its event list mapped to activity
labels. This is the classifier projection underlying control-flow discovery
(van der Aalst 2016, §4.2). -/
def Trace.activities {α : Type} (t : Trace α) : List α :=
  t.events.map Event.activity


/-- The activity projection preserves length: one activity label per event. -/
theorem Trace.activities_length {α : Type} (t : Trace α) :
    t.activities.length = t.events.length := by
  simp [Trace.activities]


/-- The empty trace is (vacuously) monotone. -/
theorem Trace.monotone_nil {α : Type} (c : String) :
    Trace.Monotone (α := α) ⟨c, []⟩ := by
  simp [Trace.Monotone]


/-- A one-event trace is monotone. -/
theorem Trace.monotone_singleton {α : Type} (c : String) (e : Event α) :
    Trace.Monotone ⟨c, [e]⟩ := by
  simp [Trace.Monotone]


/-- A constant trace (the same event replicated) is monotone, since
timestamp order is reflexive. -/
theorem Trace.monotone_replicate {α : Type} (c : String) (n : ℕ) (e : Event α) :
    Trace.Monotone ⟨c, List.replicate n e⟩ :=
  List.isChain_replicate_of_rel n (le_refl e.timestamp)


/-- Concatenation law for monotone traces: the concatenation is monotone iff
both halves are monotone and the seam respects timestamp order
(last of the first half ≤ head of the second half). Direct instance of
`List.isChain_append`. -/
theorem Trace.monotone_append {α : Type} (c : String) (l₁ l₂ : List (Event α)) :
    Trace.Monotone ⟨c, l₁ ++ l₂⟩ ↔
      Trace.Monotone ⟨c, l₁⟩ ∧ Trace.Monotone ⟨c, l₂⟩ ∧
        ∀ x ∈ l₁.getLast?, ∀ y ∈ l₂.head?, x.timestamp ≤ y.timestamp :=
  List.isChain_append


/-- Monotonicity is inherited by sublists (timestamp order is transitive), so
any subtrace of a valid trace is valid — the sublist-stability of the
`NonMonotonicTrace` law in `wasm4pm-compat/src/eventlog.rs`. -/
theorem Trace.monotone_sublist {α : Type} {c c' : String} {l₁ l₂ : List (Event α)}
    (h : Trace.Monotone ⟨c, l₂⟩) (hs : l₁.Sublist l₂) :
    Trace.Monotone ⟨c', l₁⟩ := by
  haveI : Trans (fun a b : Event α => a.timestamp ≤ b.timestamp)
      (fun a b : Event α => a.timestamp ≤ b.timestamp)
      (fun a b : Event α => a.timestamp ≤ b.timestamp) :=
    ⟨fun hab hbc => le_trans hab hbc⟩
  exact List.IsChain.sublist h hs


/-- The activity projection distributes over trace concatenation (the
classifier projection is a list homomorphism; van der Aalst 2016, §4.2). -/
theorem Trace.activities_append {α : Type} (c : String) (l₁ l₂ : List (Event α)) :
    Trace.activities ⟨c, l₁ ++ l₂⟩ =
      Trace.activities ⟨c, l₁⟩ ++ Trace.activities ⟨c, l₂⟩ := by
  simp [Trace.activities]


/-- Since timestamp order is transitive, adjacent-pair monotonicity is
equivalent to all-pairs monotonicity — the `NonMonotonicTrace` law of
`wasm4pm-compat/src/eventlog.rs` checks adjacent pairs but guarantees global
order. -/
theorem Trace.monotone_iff_pairwise {α : Type} (t : Trace α) :
    Trace.Monotone t ↔ t.events.Pairwise (fun a b => a.timestamp ≤ b.timestamp) := by
  haveI : IsTrans (Event α) (fun a b => a.timestamp ≤ b.timestamp) :=
    ⟨fun _ _ _ hab hbc => le_trans hab hbc⟩
  exact List.isChain_iff_pairwise



end ProcInt
