-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib

/-! # ProcInt.Logs.Xes

XES interchange shapes (IEEE 1849-2016): the discrete attribute-value alphabet (string/int/bool/timestamp), keyed attributes, event classifiers (named key lists), and the standard lifecycle-transition alphabet with a proven parse/print round trip. Port of wasm4pm-compat/src/event_log.rs (AttributeValue, Attribute, EventLogClassifier) and src/xes.rs (XesLifecycleTransition). -/

namespace ProcInt

/-- XES attribute values (IEEE 1849-2016 attribute type alphabet, restricted to
the discrete core): string, integer, boolean, and timestamp. Port of the
`AttributeValue` ADT in `wasm4pm-compat/src/event_log.rs`. -/
inductive XesValue where
  | str : String → XesValue
  | int : ℤ → XesValue
  | bool : Bool → XesValue
  | timestamp : ℕ → XesValue


/-- A XES attribute: a namespaced key (e.g. `concept:name`) paired with a
value. Port of `wasm4pm-compat/src/event_log.rs::Attribute` and the key/value
attribute bags of `wasm4pm-compat/src/xes.rs::XesEvent`. -/
structure XesAttribute where
  key : String
  value : XesValue


/-- A XES event classifier: a named list of attribute keys whose combined
values identify an event class (IEEE 1849-2016 §7.2). Port of
`wasm4pm-compat/src/event_log.rs::EventLogClassifier` (name, keys). -/
structure XesClassifier where
  name : String
  keys : List String


/-- The standard `lifecycle:transition` alphabet of IEEE 1849-2016. Port of
`wasm4pm-compat/src/xes.rs::XesLifecycleTransition` (14 variants). -/
inductive XesLifecycleTransition where
  | schedule | assign | start | suspend | resume | inProgress
  | abort | withdraw | complete | unknown | autoSkip | manualSkip
  | reassign | plan


/-- The canonical `lifecycle:transition` attribute string of a transition
(IEEE 1849-2016); mirrors `XesLifecycleTransition::as_str` in
`wasm4pm-compat/src/xes.rs`. -/
def XesLifecycleTransition.asString : XesLifecycleTransition → String
  | .schedule => "schedule"
  | .assign => "assign"
  | .start => "start"
  | .suspend => "suspend"
  | .resume => "resume"
  | .inProgress => "inprogress"
  | .abort => "abort"
  | .withdraw => "withdraw"
  | .complete => "complete"
  | .unknown => "unknown"
  | .autoSkip => "autoskip"
  | .manualSkip => "manualskip"
  | .reassign => "reassign"
  | .plan => "plan"


/-- Parse a `lifecycle:transition` value into the standard alphabet, refusing
(`none`) values outside it; mirrors `XesLifecycleTransition::parse` in
`wasm4pm-compat/src/xes.rs`. -/
def XesLifecycleTransition.parse : String → Option XesLifecycleTransition
  | "schedule" => some .schedule
  | "assign" => some .assign
  | "start" => some .start
  | "suspend" => some .suspend
  | "resume" => some .resume
  | "inprogress" => some .inProgress
  | "abort" => some .abort
  | "withdraw" => some .withdraw
  | "complete" => some .complete
  | "unknown" => some .unknown
  | "autoskip" => some .autoSkip
  | "manualskip" => some .manualSkip
  | "reassign" => some .reassign
  | "plan" => some .plan
  | _ => none


/-- Round-trip law: parsing the canonical string of a lifecycle transition
recovers the transition. This is the doctest contract of
`XesLifecycleTransition::parse` in `wasm4pm-compat/src/xes.rs`. -/
theorem XesLifecycleTransition.parse_asString (t : XesLifecycleTransition) :
    XesLifecycleTransition.parse t.asString = some t := by
  cases t <;> rfl


/-- The canonical string encoding of lifecycle transitions is injective
(distinct transitions have distinct `lifecycle:transition` values) — a
corollary of the round-trip law. -/
theorem XesLifecycleTransition.asString_injective :
    Function.Injective XesLifecycleTransition.asString := by
  intro a b h
  have ha := XesLifecycleTransition.parse_asString a
  rw [h, XesLifecycleTransition.parse_asString b] at ha
  exact (Option.some_inj.mp ha).symm


/-- Converse round trip: `parse` succeeds only on canonical strings, and
printing its result recovers the input — together with `parse_asString` this
makes `asString`/`parse` a partial bijection onto the IEEE 1849-2016
lifecycle alphabet (contract of `XesLifecycleTransition::parse` in
`wasm4pm-compat/src/xes.rs`). -/
theorem XesLifecycleTransition.asString_parse {s : String} {t : XesLifecycleTransition}
    (h : XesLifecycleTransition.parse s = some t) : t.asString = s := by
  unfold XesLifecycleTransition.parse at h
  split at h <;> simp_all [XesLifecycleTransition.asString] <;> subst h <;> rfl



end ProcInt
