-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib
import ProcInt.Ocel.Core

/-! # ProcInt.Ocel.Lifecycle

Object lifecycles over OCEL 2.0 logs: the created/active/archived phase lattice with well-formed transition relation (induced by ObjectTypeCardinality created-by/terminated-by event types, wasm4pm-compat src/ocel.rs), and the lifecycle of an object as its events sorted by time — time-orderedness stated as a Pairwise Prop (arXiv 2403.01975). -/

namespace ProcInt

/-- Object lifecycle phase (wasm4pm-compat src/ocel.rs ObjectTypeCardinality:
created-by events open a lifecycle, terminated-by events close it; the phase
lattice is created → active → archived). -/
inductive LifecyclePhase where
  | created
  | active
  | archived
deriving DecidableEq, Repr

/-- Well-formed lifecycle transitions: an object activates once after creation
and archives once from activity. This is the transition relation induced by the
created-by / terminated-by event types of ObjectTypeCardinality. -/
inductive LifecycleStep : LifecyclePhase → LifecyclePhase → Prop
  | activate : LifecycleStep .created .active
  | archive : LifecycleStep .active .archived

/-- Lifecycle transitions are irreflexive: no phase steps to itself. -/
theorem lifecycleStep_irrefl (p : LifecyclePhase) : ¬ LifecycleStep p p := by
  intro h
  cases h

/-- The archived phase is terminal: no lifecycle step leaves it. -/
theorem archived_terminal (p : LifecyclePhase) : ¬ LifecycleStep .archived p := by
  intro h
  cases h

/-- A list of events is time-ordered when it is sorted by the OCEL timestamp
map (OCEL 2.0: the lifecycle of an object is its events sorted by time). -/
def OCEL.TimeOrdered {E O ET OT Q V : Type}
    (L : OCEL E O ET OT Q V) (es : List E) : Prop :=
  es.Pairwise (fun a b => L.time a ≤ L.time b)

/-- es is a lifecycle of object o when it is a permutation of the events of o
that is time-ordered (OCEL 2.0: lifecycle = events of o sorted by time;
wasm4pm-compat src/ocel.rs fn object_attr_timeline is the attribute analog). -/
def OCEL.IsLifecycle {E O ET OT Q V : Type} [DecidableEq O]
    (L : OCEL E O ET OT Q V) (o : O) (es : List E) : Prop :=
  es.Perm (L.eventsOf o) ∧ L.TimeOrdered es

/-- The empty event list is trivially time-ordered. -/
theorem OCEL.timeOrdered_nil {E O ET OT Q V : Type}
    (L : OCEL E O ET OT Q V) : L.TimeOrdered ([] : List E) :=
  List.Pairwise.nil

/-- Any single event is trivially time-ordered. -/
theorem OCEL.timeOrdered_singleton {E O ET OT Q V : Type}
    (L : OCEL E O ET OT Q V) (e : E) : L.TimeOrdered [e] :=
  List.pairwise_singleton (fun a b => L.time a ≤ L.time b) e


end ProcInt
