-- Hand-authored. Not rendered by ggen. Not ledgered in .mfact/artifacts.toml.
-- Edits here are ordinary code review, not artifact drift.
import ProcInt.Playground.Multifractal.Spectrum
import Mathlib.Dynamics.BirkhoffSum.Average

/-!
# ProcInt.Playground.Multifractal.BirkhoffSpectrum

Dynamical level sets and spectra generated by convergence of Birkhoff averages.
-/

namespace ProcInt.Playground.Multifractal

open Filter
open scoped Topology

variable {X B : Type*}

/-- The orbit-average observation sequence already manufactured by mathlib's `birkhoffAverage`. -/
noncomputable def birkhoffAverageSequence (T : X → X) (φ : X → ℝ) (x : X) : ℕ → ℝ :=
  fun n => birkhoffAverage ℝ T φ n x

/-- The Birkhoff average of `φ` along `T` exists at `x` and equals `α`. -/
def HasBirkhoffAverage (T : X → X) (φ : X → ℝ) (x : X) (α : ℝ) : Prop :=
  Tendsto (birkhoffAverageSequence T φ x) atTop (𝓝 α)

/-- Points whose Birkhoff average equals `α`. -/
def birkhoffLevelSet (T : X → X) (φ : X → ℝ) (α : ℝ) : Set X :=
  {x | HasBirkhoffAverage T φ x α}

/-- Evaluate an arbitrary invariant on a Birkhoff level set. -/
def birkhoffSpectrumAt
    (I : Set X → B) (T : X → X) (φ : X → ℝ) (α : ℝ) : B :=
  I (birkhoffLevelSet T φ α)

/-- Full Birkhoff spectrum `α ↦ I(E_α)`. -/
def birkhoffSpectrum
    (I : Set X → B) (T : X → X) (φ : X → ℝ) : ℝ → B :=
  fun α => birkhoffSpectrumAt I T φ α

@[simp]
theorem mem_birkhoffLevelSet_iff
    (T : X → X) (φ : X → ℝ) (x : X) (α : ℝ) :
    x ∈ birkhoffLevelSet T φ α ↔ HasBirkhoffAverage T φ x α :=
  Iff.rfl

end ProcInt.Playground.Multifractal
