-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib
import ProcInt.Petri.Reachability

/-! # ProcInt.Petri.Boundedness

Behavioural properties over the reachability set: k-boundedness (every reachable marking carries at most k tokens per place) and L4-liveness (every transition can always eventually fire again) — Murata 1989, section IV; the two properties whose conjunction characterizes WF-net soundness (van der Aalst 1997, Lemma 8). -/

namespace ProcInt

/-- A net is k-bounded from M₀ when every reachable marking carries at most
k tokens in every place (Murata 1989, section IV, boundedness; k = 1 is
safeness). -/
def PetriNet.Bounded {P T : Type} (N : PetriNet P T) (M₀ : Marking P) (k : ℕ) : Prop :=
  ∀ M, N.Reaches M₀ M → ∀ p, M p ≤ k

/-- A net is live from M₀ when from every reachable marking, every transition
can eventually be enabled again (Murata 1989, section IV, L4-liveness — the
liveness clause of van der Aalst 1997 WF-net soundness). -/
def PetriNet.Live {P T : Type} (N : PetriNet P T) (M₀ : Marking P) : Prop :=
  ∀ M, N.Reaches M₀ M → ∀ t, ∃ M', N.Reaches M M' ∧ N.Enabled M' t


end ProcInt
