-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib
import ProcInt.Petri.Net

/-! # ProcInt.Petri.Firing

The transition (firing) rule: enabledness, the fire function via truncated Finsupp subtraction, the one-step relation, determinism of firing, and the single-firing token-conservation identity underlying the state equation (Murata 1989, section II.C). -/

namespace ProcInt

/-- Transition t is enabled at marking M when every input place carries at
least the required tokens (Murata 1989, firing rule, condition (1)). -/
def PetriNet.Enabled {P T : Type} (N : PetriNet P T) (M : Marking P) (t : T) : Prop :=
  N.pre t ≤ M

/-- Fire transition t at marking M: consume the pre-multiset (truncated
subtraction) and produce the post-multiset (Murata 1989, firing rule,
condition (2)). Noncomputable because Finsupp addition is. -/
noncomputable def PetriNet.fire {P T : Type} (N : PetriNet P T) (M : Marking P) (t : T) : Marking P :=
  M - N.pre t + N.post t

/-- One firing step: t is enabled at M and M' is the result of firing it
(Murata 1989, the transition (firing) rule). -/
def PetriNet.Step {P T : Type} (N : PetriNet P T) (M : Marking P) (t : T) (M' : Marking P) : Prop :=
  N.Enabled M t ∧ M' = N.fire M t

/-- Firing is deterministic: one transition fired at one marking yields a
unique successor marking (immediate from the firing rule, Murata 1989). -/
theorem PetriNet.step_deterministic {P T : Type} (N : PetriNet P T)
    {M M₁ M₂ : Marking P} {t : T}
    (h₁ : N.Step M t M₁) (h₂ : N.Step M t M₂) : M₁ = M₂ := by
  rw [h₁.2, h₂.2]

/-- Firing under enabledness satisfies the token-conservation identity
fire M t + pre t = M + post t — the Finsupp form of the state-equation
increment for a single firing (Murata 1989, section II.C). -/
theorem PetriNet.fire_add_pre {P T : Type} (N : PetriNet P T)
    {M : Marking P} {t : T} (h : N.Enabled M t) :
    N.fire M t + N.pre t = M + N.post t := by
  have h' : N.pre t ≤ M := h
  show M - N.pre t + N.post t + N.pre t = M + N.post t
  rw [add_right_comm, tsub_add_cancel_of_le h']


end ProcInt
