-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib
import ProcInt.Petri.Net
import ProcInt.Petri.Firing
import ProcInt.Petri.Reachability
import ProcInt.Petri.StateEquation

/-! # ProcInt.Petri.Invariants

Murata 1989 Section IV-C place and transition invariants: a P-invariant is a place weighting y with yᵀA = 0, proven conserved along single steps and along the full reachability relation (Murata Theorem 15) by induction on ReflTransGen; a T-invariant is taken in Parikh form over a firing sequence (summed incidence columns vanish) and the reproduction property M' = M (Murata Theorem 16) is proven via injectivity of the ℤ-cast. -/

namespace ProcInt

/-- Integer pairing ⟪y, v⟫ = Σ_p y(p)·v(p) used to evaluate place weightings against
incidence columns (Murata 1989, Section IV-C). -/
def weighSum {P : Type} (y : P → ℤ) (v : P →₀ ℤ) : ℤ :=
  v.sum fun p n => y p * n

/-- The pairing ⟪y, ·⟫ is additive in its vector argument. -/
theorem weighSum_add {P : Type} (y : P → ℤ) (v w : P →₀ ℤ) :
    weighSum y (v + w) = weighSum y v + weighSum y w := by
  classical
  unfold weighSum
  exact Finsupp.sum_add_index (fun p _ => mul_zero (y p)) (fun p _ m n => mul_add (y p) m n)

/-- P-invariant (place invariant): a weighting y with yᵀA = 0, i.e. ⟪y, A·eₜ⟫ = 0 for every
transition t (Murata 1989, Section IV-C, Eq. (13)). -/
def PetriNet.IsPInvariant {P T : Type} (N : PetriNet P T) (y : P → ℤ) : Prop :=
  ∀ t, weighSum y (N.change t) = 0

/-- Conservation along a single step: a P-invariant weighting is unchanged by any firing
(Murata 1989, Theorem 15: yᵀM = yᵀM₀ for reachable M). -/
theorem PetriNet.pInvariant_step {P T : Type} (N : PetriNet P T) {y : P → ℤ}
    (hy : N.IsPInvariant y) {M M' : Marking P} {t : T} (h : N.Step M t M') :
    weighSum y (Marking.toInt M') = weighSum y (Marking.toInt M) := by
  rw [N.stateEquation_step h, weighSum_add, hy t, add_zero]

/-- Conservation along reachability: a P-invariant weighting is constant on the whole
reachability set (Murata 1989, Theorem 15). Proof by induction on ReflTransGen. -/
theorem PetriNet.pInvariant_reaches {P T : Type} (N : PetriNet P T) {y : P → ℤ}
    (hy : N.IsPInvariant y) {M M' : Marking P} (h : N.Reaches M M') :
    weighSum y (Marking.toInt M') = weighSum y (Marking.toInt M) := by
  induction h with
  | refl => rfl
  | tail _ hstep ih =>
      obtain ⟨t, hstep⟩ := hstep
      rw [N.pInvariant_step hy hstep, ih]

/-- T-invariant (transition invariant) of a firing sequence, taken in Parikh form: the summed
incidence columns of σ vanish, A·⃗σ = 0 (Murata 1989, Section IV-C, Eq. (14)). -/
def PetriNet.IsTInvariantSeq {P T : Type} (N : PetriNet P T) (σ : List T) : Prop :=
  (σ.map N.change).sum = 0

/-- Murata 1989, Theorem 16 (reproduction): a firing sequence whose Parikh vector is a
T-invariant reproduces the starting marking exactly. Uses injectivity of the ℤ-cast. -/
theorem PetriNet.tInvariant_reproduces {P T : Type} (N : PetriNet P T)
    {M M' : Marking P} {σ : List T} (h : N.FiringSeq M σ M')
    (hσ : N.IsTInvariantSeq σ) : M' = M := by
  apply Marking.toInt_injective
  rw [N.stateEquation_seq h, hσ, add_zero]


end ProcInt
