-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib
import ProcInt.Petri.Net

/-! # ProcInt.Petri.Stochastic

Stochastic Petri nets (Marsan et al. 1984 GSPN; Leemans 2019 stochastic process mining): transitions carry nonnegative rational weights (NNRat, porting the compile-time NUM/DEN fractions of StochasticArcWeight in wasm4pm-compat src/petri.rs) and an immediate/timed kind marker. The stochastic choice over a finite conflict set is weight(t) divided by the total weight; it is proven to be a probability distribution (probabilities sum to 1 and are each at most 1 when the normalizer is nonzero). -/

namespace ProcInt

/-- Kind of a stochastic transition: immediate (fires instantly when enabled, weight resolves
conflicts) or timed (fires after a stochastic delay). Ported from ImmediateTransition /
TimedTransition markers in wasm4pm-compat petri.rs; cf. Marsan et al. 1984 GSPN and
Leemans 2019 stochastic process mining. -/
inductive TransitionKind where
  | immediate : TransitionKind
  | timed : TransitionKind
deriving DecidableEq, Repr

/-- Stochastic Petri net: a Petri net whose transitions carry nonnegative rational weights
and an immediate/timed kind (Leemans 2019; GSPN of Marsan et al. 1984). Weights in ℚ≥0
port the StochasticArcWeight NUM/DEN ∈ [0,1] compile-time fractions of wasm4pm-compat. -/
structure StochasticPetriNet (P T : Type) where
  net : PetriNet P T
  weight : T → NNRat
  kind : T → TransitionKind

/-- Total weight of a finite conflict set of transitions (the normalizing constant of the
stochastic choice, Leemans 2019). -/
def StochasticPetriNet.choiceWeight {P T : Type} (S : StochasticPetriNet P T)
    (E : Finset T) : NNRat :=
  E.sum fun t => S.weight t

/-- Probability that transition t wins the stochastic choice among the conflict set E:
weight(t) / Σ over u ∈ E of weight(u) (Leemans 2019 stochastic labelled Petri nets). -/
def StochasticPetriNet.fireProb {P T : Type} (S : StochasticPetriNet P T)
    (E : Finset T) (t : T) : NNRat :=
  S.weight t / S.choiceWeight E

/-- The stochastic choice is a probability distribution: over any conflict set with nonzero
total weight, the firing probabilities sum to 1 (Leemans 2019). -/
theorem StochasticPetriNet.fireProb_sum {P T : Type} (S : StochasticPetriNet P T)
    (E : Finset T) (h : S.choiceWeight E ≠ 0) :
    (E.sum fun t => S.fireProb E t) = 1 := by
  unfold StochasticPetriNet.fireProb
  rw [← Finset.sum_div]
  exact div_self h

/-- Each firing probability is at most 1: a member's weight never exceeds the conflict set's
total weight (Leemans 2019). -/
theorem StochasticPetriNet.fireProb_le_one {P T : Type} (S : StochasticPetriNet P T)
    (E : Finset T) {t : T} (ht : t ∈ E)
    (h : 0 < S.choiceWeight E) : S.fireProb E t ≤ 1 := by
  rw [StochasticPetriNet.fireProb, div_le_one h]
  exact Finset.single_le_sum (fun i _ => zero_le) ht


end ProcInt
