-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib

/-! # ProcInt.Models.CausalNet

Causal nets (C-nets): the Heuristics Miner output shape with nodes, dependency arcs scored by a rational dependency measure, and input/output binding obligations, plus the dependency-measure formula and its bounds. Port of wasm4pm-compat causal_net.rs; canonical source: Weijters and Ribeiro, Flexible Heuristics Miner, IEEE CIDM 2011. -/

namespace ProcInt

/-- A causal-net binding: which combination of predecessor tasks activates
(or successor tasks is produced by) a task. Port of `causal_net.rs`
`CausalBinding` (Weijters and Ribeiro 2011, FHM C-net bindings). -/
structure CausalBinding (α : Type u) where
  sources : List α
  targets : List α

/-- A causal net (Heuristics Miner output shape): nodes, dependency arcs
scored by a rational measure, and input/output binding obligations.
Port of `causal_net.rs` `CausalNet` (Weijters and Ribeiro 2011). -/
structure CausalNet (α : Type u) where
  nodes : List α
  deps : List (α × α × ℚ)
  inputs : List (CausalBinding α)
  outputs : List (CausalBinding α)

/-- The Heuristics Miner dependency measure a ⇒ b = (|a>b| − |b>a|) / (|a>b| + |b>a| + 1),
computed in ℚ from directly-follows counts. Weijters and Ribeiro (2011), Section 2;
port of `causal_net.rs` `DependencyMeasure`. -/
def dependencyMeasure (ab ba : ℕ) : ℚ :=
  ((ab : ℚ) - (ba : ℚ)) / ((ab : ℚ) + (ba : ℚ) + 1)

/-- Structural validity of a causal net's scores: every dependency measure
lies in [-1, 1]. Port of `causal_net.rs` `CausalNetRefusal::InvalidDependencyScore`
(the Rust shape stores only nonnegative scores; the signed measure is bounded by 1). -/
def CausalNet.ScoresValid (net : CausalNet α) : Prop :=
  ∀ d ∈ net.deps, -1 ≤ d.2.2 ∧ d.2.2 ≤ 1

/-- The dependency measure is strictly below 1: the +1 in the denominator
keeps even a one-sided count from reaching certainty
(Weijters and Ribeiro 2011, Section 2). -/
theorem dependencyMeasure_lt_one (ab ba : ℕ) : dependencyMeasure ab ba < 1 := by
  unfold dependencyMeasure
  rw [div_lt_one (by positivity)]
  have hba : (0 : ℚ) ≤ (ba : ℚ) := Nat.cast_nonneg ba
  linarith

/-- The dependency measure is strictly above -1 (dual bound). -/
theorem neg_one_lt_dependencyMeasure (ab ba : ℕ) : -1 < dependencyMeasure ab ba := by
  unfold dependencyMeasure
  rw [lt_div_iff₀ (by positivity)]
  have hab : (0 : ℚ) ≤ (ab : ℚ) := Nat.cast_nonneg ab
  linarith

/-- Antisymmetry of the dependency measure: a ⇒ b = −(b ⇒ a)
(Weijters and Ribeiro 2011, Section 2). -/
theorem dependencyMeasure_antisymm (ab ba : ℕ) :
    dependencyMeasure ab ba = - dependencyMeasure ba ab := by
  unfold dependencyMeasure
  rw [← neg_div]
  ring_nf

/-- Symmetric counts give zero causal strength: a ⇒ a with equal
directly-follows counts in both directions is 0. -/
theorem dependencyMeasure_self (n : ℕ) : dependencyMeasure n n = 0 := by
  unfold dependencyMeasure
  simp


end ProcInt
