name = "random_walk"
version = "0.1.0"
defaultTargets = ["RandomWalk"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "fabf563a7c95a166b8d7b6efca11c8b4dc9d911f"

[[lean_lib]]
name = "RandomWalk"
