-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib
import ProcInt.Ocel.Core
import ProcInt.Ocel.Relations

/-! # ProcInt.Ocpq.Query

OCPQ predicate ADT (OCPQ Section 4 BASIC_L; wasm4pm-compat src/ocpq.rs enum PredicateKind): E2O and O2O relation predicates plus an anonymous cardinality bound on an event's object projection, with satisfaction against an OCEL log as a Prop and decidable satisfaction under DecidableEq assumptions. -/

namespace ProcInt

/-- OCPQ predicate ADT (wasm4pm-compat src/ocpq.rs enum PredicateKind, OCPQ
Section 4 BASIC_L): an event-to-object relation predicate E2O(e, o, q), an
object-to-object relation predicate O2O(src, q, dst), and an anonymous
cardinality bound on the number of objects of an event, with inclusive
[min, max] window. -/
inductive OcpqPredicate (E O Q : Type) where
  | e2oRel (e : E) (o : O) (q : Q)
  | o2oRel (src : O) (q : Q) (dst : O)
  | cardObjects (e : E) (min max : ℕ)

/-- Satisfaction of an OCPQ predicate against an OCEL log, as a Prop:
E2O/O2O predicates assert membership of the qualified triple in the log's
relation tables; cardObjects asserts the inclusive count window on the event's
E2O projection (OCPQ Section 4 semantics; wasm4pm-compat src/ocpq.rs). -/
def OcpqPredicate.Sat {E O ET OT Q V : Type} [DecidableEq E]
    (L : OCEL E O ET OT Q V) : OcpqPredicate E O Q → Prop
  | .e2oRel e o q => (e, q, o) ∈ L.e2o
  | .o2oRel s q d => (s, q, d) ∈ L.o2o
  | .cardObjects e mn mx =>
      mn ≤ (L.objectsOf e).length ∧ (L.objectsOf e).length ≤ mx

/-- Satisfaction is decidable when event, object and qualifier types have
decidable equality: relation predicates reduce to decidable list membership,
cardinality predicates to decidable ℕ comparisons. -/
instance OcpqPredicate.instDecidableSat {E O ET OT Q V : Type}
    [DecidableEq E] [DecidableEq O] [DecidableEq Q]
    (L : OCEL E O ET OT Q V) : (p : OcpqPredicate E O Q) → Decidable (p.Sat L)
  | .e2oRel e o q => inferInstanceAs (Decidable ((e, q, o) ∈ L.e2o))
  | .o2oRel s q d => inferInstanceAs (Decidable ((s, q, d) ∈ L.o2o))
  | .cardObjects e mn mx =>
      inferInstanceAs
        (Decidable (mn ≤ (L.objectsOf e).length ∧ (L.objectsOf e).length ≤ mx))

/-- E2O predicate satisfaction is exactly membership of the qualified triple in
the log's E2O table (definitional characterization). -/
theorem OcpqPredicate.sat_e2oRel_iff {E O ET OT Q V : Type} [DecidableEq E]
    (L : OCEL E O ET OT Q V) (e : E) (o : O) (q : Q) :
    (OcpqPredicate.e2oRel e o q).Sat L ↔ (e, q, o) ∈ L.e2o :=
  Iff.rfl

/-- A satisfied E2O predicate certifies the object projection: satisfaction
puts the related object into objectsOf of the related event. -/
theorem OcpqPredicate.sat_e2oRel_mem {E O ET OT Q V : Type} [DecidableEq E]
    (L : OCEL E O ET OT Q V) {e : E} {o : O} {q : Q}
    (h : (OcpqPredicate.e2oRel e o q).Sat L) : o ∈ L.objectsOf e :=
  L.mem_objectsOf h


end ProcInt
