-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib
import ProcInt.Conformance.Moves

/-! # ProcInt.Conformance.Alignment

Alignments, projections, and alignment cost (Carmona et al., Conformance Checking, Springer 2018, ch. 7; Adriansyah 2011). An alignment is a sequence of moves whose log projection reproduces the observed trace; its model projection is a candidate model run, stated abstractly against a trace-language predicate. Cost is the sum of per-move standard costs; cost-0 alignments characterize perfectly fitting traces. -/

namespace ProcInt

/-- Total standard cost of an alignment: the sum of the per-move costs
(Carmona et al. 2018, Def. of alignment cost; Adriansyah 2011). -/
def alignmentCost {α T : Type*} (γ : List (Move α T)) : ℕ :=
  (γ.map Move.cost).sum

/-- Log projection of an alignment: the sequence of activities contributed by
synchronous and log-only moves, dropping model-only and silent moves (Carmona
et al. 2018, projection onto the log component). -/
def logProjection {α T : Type*} (γ : List (Move α T)) : List α :=
  γ.filterMap fun m =>
    match m with
    | .sync a _ => some a
    | .logOnly a => some a
    | .modelOnly _ => none
    | .silentModel _ => none

/-- Model projection of an alignment: the sequence of transitions contributed
by synchronous, model-only, and silent-model moves (Carmona et al. 2018,
projection onto the model component; silent transitions remain in the model
run). -/
def modelProjection {α T : Type*} (γ : List (Move α T)) : List T :=
  γ.filterMap fun m =>
    match m with
    | .sync _ t => some t
    | .logOnly _ => none
    | .modelOnly t => some t
    | .silentModel t => some t

/-- γ is an alignment of the trace σ when its log projection reproduces σ
exactly (Carmona et al. 2018, Def. 7.1 log side; the model side is stated
against a trace-language predicate in IsCompleteAlignment). -/
def IsAlignment {α T : Type*} (γ : List (Move α T)) (σ : List α) : Prop :=
  logProjection γ = σ

/-- γ is a complete alignment of σ against a model whose runs are described by
the trace-language predicate L: the log projection equals σ and the model
projection is a run admitted by L (Carmona et al. 2018; Adriansyah 2011,
complete alignments end in a final marking). -/
def IsCompleteAlignment {α T : Type*} (L : List T → Prop)
    (γ : List (Move α T)) (σ : List α) : Prop :=
  logProjection γ = σ ∧ L (modelProjection γ)

/-- Alignment cost is additive under concatenation of alignments. -/
theorem alignmentCost_append {α T : Type*} (γ₁ γ₂ : List (Move α T)) :
    alignmentCost (γ₁ ++ γ₂) = alignmentCost γ₁ + alignmentCost γ₂ := by
  simp [alignmentCost]

/-- An alignment has zero total cost iff every move in it is cost-free, i.e.
synchronous or silent-model (Carmona et al. 2018: cost-0 alignments witness
perfectly fitting traces). -/
theorem alignmentCost_zero_iff_all_costfree {α T : Type*} (γ : List (Move α T)) :
    alignmentCost γ = 0 ↔ ∀ m ∈ γ, m.cost = 0 := by
  simp [alignmentCost, List.sum_eq_zero_iff]

/-- The log projection never exceeds the alignment in length: each move
contributes at most one activity. -/
theorem logProjection_length_le {α T : Type*} (γ : List (Move α T)) :
    (logProjection γ).length ≤ γ.length :=
  List.length_filterMap_le _ _


end ProcInt
