-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib

/-! # ProcInt.Conformance.TokenReplay

Token-based replay fitness (Rozinat and van der Aalst, Conformance Checking of Processes Based on Monitoring Real Behavior, Information Systems 33(1), 2008). ReplayCounts carries produced/consumed/missing/remaining token tallies with the structural invariants missing ≤ consumed and remaining ≤ produced as proof fields; fitness is the exact rational (1/2)(1 - missing/consumed) + (1/2)(1 - remaining/produced), proved to lie in [0,1] — the Lean form of the Between01 metric law in wasm4pm-compat docs/METRIC_LAW.md. Ports TokenReplayResult from wasm4pm-compat src/conformance.rs. -/

namespace ProcInt

/-- Token-replay counts (Rozinat and van der Aalst 2008, Conformance Checking
of Processes Based on Monitoring Real Behavior): tokens produced, consumed,
missing (had to be created artificially to fire), and remaining (left behind
after replay). Missing tokens are a subset of consumed and remaining a subset
of produced, recorded as proof fields. Ported from TokenReplayResult in
wasm4pm-compat src/conformance.rs. -/
structure ReplayCounts where
  produced : ℕ
  consumed : ℕ
  missing : ℕ
  remaining : ℕ
  missing_le : missing ≤ consumed
  remaining_le : remaining ≤ produced

/-- If m ≤ n then 1 - m/n is nonnegative in ℚ; the n = 0 case forces m = 0 and
uses the ℚ convention x/0 = 0. Support lemma for the Rozinat-Aalst fitness
bounds. -/
theorem oneSubRatio_nonneg {m n : ℕ} (h : m ≤ n) : 0 ≤ 1 - (m : ℚ) / n := by
  rcases Nat.eq_zero_or_pos n with hn | hn
  · have hm : m = 0 := by omega
    subst hm
    subst hn
    norm_num
  · have hpos : (0 : ℚ) < n := by exact_mod_cast hn
    have hle : (m : ℚ) / n ≤ 1 := (div_le_one hpos).mpr (by exact_mod_cast h)
    linarith

/-- 1 - m/n never exceeds 1 in ℚ, since m/n ≥ 0 for natural m, n (with the
x/0 = 0 convention). Support lemma for the Rozinat-Aalst fitness bounds. -/
theorem oneSubRatio_le_one (m n : ℕ) : 1 - (m : ℚ) / n ≤ 1 := by
  have hnn : (0 : ℚ) ≤ (m : ℚ) / n := by positivity
  linarith

/-- Token-replay fitness (Rozinat and van der Aalst 2008, Def. of fitness):
f = (1/2)(1 - missing/consumed) + (1/2)(1 - remaining/produced), as an exact
rational. The ℚ convention x/0 = 0 makes the formula total; each degenerate
denominator forces its numerator to 0 via the ReplayCounts proof fields. -/
def fitness (c : ReplayCounts) : ℚ :=
  (1 - (c.missing : ℚ) / (c.consumed : ℚ)) / 2 +
    (1 - (c.remaining : ℚ) / (c.produced : ℚ)) / 2

/-- Token-replay fitness is nonnegative (Rozinat-Aalst 2008; lower bound of
the [0,1] metric law in wasm4pm-compat docs/METRIC_LAW.md). -/
theorem fitness_nonneg (c : ReplayCounts) : 0 ≤ fitness c := by
  have h1 := oneSubRatio_nonneg c.missing_le
  have h2 := oneSubRatio_nonneg c.remaining_le
  unfold fitness
  linarith

/-- Token-replay fitness is at most 1 (Rozinat-Aalst 2008; upper bound of the
[0,1] metric law in wasm4pm-compat docs/METRIC_LAW.md). -/
theorem fitness_le_one (c : ReplayCounts) : fitness c ≤ 1 := by
  have h1 := oneSubRatio_le_one c.missing c.consumed
  have h2 := oneSubRatio_le_one c.remaining c.produced
  unfold fitness
  linarith

/-- The Rozinat-Aalst token-replay fitness always lies in the unit interval:
0 ≤ fitness ∧ fitness ≤ 1. This is the Lean form of the Between01 metric law
of wasm4pm-compat docs/METRIC_LAW.md. -/
theorem fitness_mem_unitInterval (c : ReplayCounts) :
    0 ≤ fitness c ∧ fitness c ≤ 1 :=
  ⟨fitness_nonneg c, fitness_le_one c⟩

/-- A perfect replay — no missing and no remaining tokens — has fitness
exactly 1 (Rozinat-Aalst 2008; mirrors calculate_fitness(4,4,0,0) = 1.0 in
wasm4pm-compat src/conformance.rs). -/
theorem fitness_perfect (c : ReplayCounts)
    (hm : c.missing = 0) (hr : c.remaining = 0) : fitness c = 1 := by
  unfold fitness
  rw [hm, hr]
  norm_num


end ProcInt
