-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib

/-! # ProcInt.Analytics.Causality

Cross-object causal structure: directed causal links, causal chains with an adjacent-link connectedness invariant, and the four-way causal-consistency verdict. Ported from wasm4pm-compat causality.rs (CausalLink, CausalChain, CausalConsistency). Canon: happened-before causality in object-centric event data; posets constraint (no cycles, no contradictions). -/

namespace ProcInt

/-- A directed causal link between two items (causality.rs `CausalLink`). -/
structure CausalLink (α : Type*) where
  source : α
  target : α

/-- A causal chain: a list of causal links (causality.rs `CausalChain`). -/
structure CausalChain (α : Type*) where
  links : List (CausalLink α)

/-- Adjacent links agree: each link's target is the next link's source
(the connectedness invariant of causality.rs `CausalChain`). -/
def linked {α : Type*} : List (CausalLink α) → Prop
  | [] => True
  | [_] => True
  | l1 :: l2 :: rest => l1.target = l2.source ∧ linked (l2 :: rest)

/-- Chain consistency Prop (causality.rs `CausalConsistency::Consistent`). -/
def CausalChain.Consistent {α : Type*} (c : CausalChain α) : Prop :=
  linked c.links

/-- Verdict of a causal-consistency check (causality.rs `CausalConsistency`):
consistent, has cycles, has contradictions, or not yet established. -/
inductive CausalConsistency where
  | consistent
  | hasCycles
  | hasContradictions
  | unknown
deriving DecidableEq, Repr

/-- The empty chain is linked (causality.rs `CausalChain` base case). -/
theorem linked_nil {α : Type*} : linked ([] : List (CausalLink α)) := by
  simp [linked]

/-- A singleton chain is linked (causality.rs `CausalChain` unit case). -/
theorem linked_singleton {α : Type*} (l : CausalLink α) : linked [l] := by
  simp [linked]

/-- The tail of a linked chain is linked (chain suffix closure). -/
theorem linked_tail {α : Type*} {l1 l2 : CausalLink α} {rest : List (CausalLink α)}
    (h : linked (l1 :: l2 :: rest)) : linked (l2 :: rest) := by
  simp [linked] at h
  exact h.2


end ProcInt
