-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib

/-! # ProcInt.Analytics.Correlation

Event correlation across logs: the four-way correlation schema (by case, by object, by timestamp, by attribute), typed correlation keys, and correlated logs whose pairing invariant is key agreement under two key projections. Ported from wasm4pm-compat correlation.rs (CorrelationSchema, CorrelationKey, CorrelatedLog). -/

namespace ProcInt

/-- Event-correlation schema (correlation.rs `CorrelationSchema`):
by case id, by shared object, by timestamp proximity, by attribute equality. -/
inductive CorrelationSchema where
  | byCase
  | byObject
  | byTimestamp
  | byAttribute
deriving DecidableEq, Repr

/-- A correlation key: a schema tag plus the key value (correlation.rs `CorrelationKey`). -/
structure CorrelationKey (κ : Type*) where
  schema : CorrelationSchema
  key : κ

/-- A correlated log: paired items from two logs with key projections
(correlation.rs `CorrelatedLog`). -/
structure CorrelatedLog (α β κ : Type*) where
  keyA : α → κ
  keyB : β → κ
  pairs : List (α × β)

/-- Correlation invariant: every pair agrees on its correlation key
(correlation.rs `CorrelationWitness` semantics). -/
def CorrelatedLog.Correlated {α β κ : Type*} (log : CorrelatedLog α β κ) : Prop :=
  ∀ p ∈ log.pairs, log.keyA p.1 = log.keyB p.2

/-- The empty correlated log is correlated (vacuous key agreement). -/
theorem correlated_empty {α β κ : Type*} (keyA : α → κ) (keyB : β → κ) :
    CorrelatedLog.Correlated ⟨keyA, keyB, []⟩ := by
  intro p hp
  cases hp

/-- Extending a correlated log with a key-agreeing pair preserves correlation. -/
theorem correlated_cons {α β κ : Type*} {log : CorrelatedLog α β κ}
    (h : log.Correlated) {a : α} {b : β} (hab : log.keyA a = log.keyB b) :
    CorrelatedLog.Correlated ⟨log.keyA, log.keyB, (a, b) :: log.pairs⟩ := by
  intro p hp
  rcases List.mem_cons.mp hp with h1 | h2
  · subst h1
    exact hab
  · exact h p h2


end ProcInt
