-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib

/-! # ProcInt.Analytics.Lifecycle

Object lifecycle law for object-centric process mining: the five phases (created, active, modified, archived, deleted), lawful transitions as an inductive Prop mirroring the Rust typestate impls, and terminality theorems (deleted is terminal, created is never re-entered, archived only deletes). Ported from wasm4pm-compat object_lifecycle.rs (ObjectLifecyclePhase, LifecycleTransition, LifecycledObject). Canon: OCEL 2.0 object lifecycles. -/

namespace ProcInt

/-- Object lifecycle phases (object_lifecycle.rs `ObjectLifecyclePhase`):
created, active, modified, archived, deleted (terminal). OCEL 2.0 object lifecycle. -/
inductive ObjectLifecyclePhase where
  | created
  | active
  | modified
  | archived
  | deleted
deriving DecidableEq, Repr

/-- Lawful lifecycle transitions as an inductive Prop, mirroring the typestate
impl blocks of object_lifecycle.rs `LifecycledObject` (activate, modify,
re-modify, archive, delete). -/
inductive LifecycleTransition : ObjectLifecyclePhase → ObjectLifecyclePhase → Prop where
  | activate : LifecycleTransition .created .active
  | modify : LifecycleTransition .active .modified
  | remodify : LifecycleTransition .modified .modified
  | archiveActive : LifecycleTransition .active .archived
  | archiveModified : LifecycleTransition .modified .archived
  | delete : LifecycleTransition .archived .deleted

/-- An object tagged with its current lifecycle phase
(object_lifecycle.rs `LifecycledObject`). -/
structure LifecycledObject (α : Type*) where
  inner : α
  phase : ObjectLifecyclePhase

/-- Deleted is terminal: no transition leaves the deleted phase
(object_lifecycle.rs: no impl block on Deleted). -/
theorem deleted_terminal (p : ObjectLifecyclePhase) :
    ¬ LifecycleTransition .deleted p :=
  fun h => nomatch h

/-- No transition re-enters the created phase (creation is a one-time event). -/
theorem no_transition_to_created (p : ObjectLifecyclePhase) :
    ¬ LifecycleTransition p .created :=
  fun h => nomatch h

/-- From the archived phase, the only lawful successor is deleted
(object_lifecycle.rs: Archived exposes only delete). -/
theorem archived_only_deletes {p : ObjectLifecyclePhase}
    (h : LifecycleTransition .archived p) : p = .deleted := by
  cases h
  rfl


end ProcInt
