-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib

/-! # ProcInt.Analytics.Multiperspective

Multi-perspective process mining: the four perspectives (control-flow, data, resource, time), per-perspective ℚ weights with a normalization law (nonnegative, summing to 1), uniform weights proven normalized, and weighted score combination with the uniform-mean law. Ported from wasm4pm-compat multiperspective.rs (ProcessPerspective, PerspectiveWeight, MultiPerspectiveWeightConfig, PerspectiveCombination). Canon: Mannhardt, de Leoni, Reijers, van der Aalst 2016, Balanced Multi-Perspective Checking of Process Conformance. -/

namespace ProcInt

/-- The four process perspectives (multiperspective.rs `ProcessPerspective`):
control-flow, data, resource, time. Canon: Mannhardt et al. 2016,
balanced multi-perspective conformance checking. -/
inductive ProcessPerspective where
  | controlFlow
  | data
  | resource
  | time
deriving DecidableEq, Repr

/-- Per-perspective ℚ weights (multiperspective.rs `MultiPerspectiveWeightConfig`). -/
structure PerspectiveWeights where
  controlFlow : ℚ
  data : ℚ
  resource : ℚ
  time : ℚ

/-- Weight normalization: nonnegative weights summing to 1
(multiperspective.rs weight-sum law). -/
def PerspectiveWeights.Normalized (w : PerspectiveWeights) : Prop :=
  w.controlFlow + w.data + w.resource + w.time = 1 ∧
  0 ≤ w.controlFlow ∧ 0 ≤ w.data ∧ 0 ≤ w.resource ∧ 0 ≤ w.time

/-- The uniform weight configuration: 1/4 per perspective. -/
def uniformWeights : PerspectiveWeights :=
  ⟨1/4, 1/4, 1/4, 1/4⟩

/-- The uniform weights are normalized (decided on ℚ literals). -/
theorem uniformWeights_normalized : uniformWeights.Normalized := by
  unfold PerspectiveWeights.Normalized uniformWeights
  norm_num

/-- Weighted combination of per-perspective scores
(multiperspective.rs `PerspectiveCombination`). -/
def combinedScore (w : PerspectiveWeights) (s : ProcessPerspective → ℚ) : ℚ :=
  w.controlFlow * s .controlFlow + w.data * s .data +
    w.resource * s .resource + w.time * s .time

/-- Under uniform weights the combined score is the arithmetic mean of the
four perspective scores (Mannhardt et al. 2016 balanced combination). -/
theorem combinedScore_uniform (s : ProcessPerspective → ℚ) :
    combinedScore uniformWeights s =
      (s .controlFlow + s .data + s .resource + s .time) / 4 := by
  unfold combinedScore uniformWeights
  ring


end ProcInt
