-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib

/-! # ProcInt.Analytics.Streaming

Streaming process mining shapes: a sliding event window whose size bound is a proof-carrying field (events.length ≤ size), a push operation that evicts overflow while preserving the bound, and the online/offline analysis-context distinction. Ported from wasm4pm-compat streaming.rs (EventWindow, OnlineMonitoringContext, OfflineAnalysisContext). -/

namespace ProcInt

/-- A sliding event window with a proof-carrying size bound
(streaming.rs `EventWindow<T, SIZE>`): events.length ≤ size is a field proof. -/
structure EventWindow (α : Type*) (size : ℕ) where
  events : List α
  bounded : events.length ≤ size

/-- The empty window (streaming.rs `EventWindow::new`). -/
def EventWindow.empty (α : Type*) (size : ℕ) : EventWindow α size :=
  ⟨[], Nat.zero_le size⟩

/-- Push an event: prepend and truncate to the size bound, evicting the oldest
overflow (streaming.rs `EventWindow::push`). -/
def EventWindow.push {α : Type*} {size : ℕ} (w : EventWindow α size) (e : α) :
    EventWindow α size :=
  ⟨(e :: w.events).take size, by rw [List.length_take]; omega⟩

/-- The window bound is invariant under push (window length bound law). -/
theorem push_bounded {α : Type*} {size : ℕ} (w : EventWindow α size) (e : α) :
    (w.push e).events.length ≤ size :=
  (w.push e).bounded

/-- The empty window holds no events (streaming.rs `EventWindow::new`). -/
theorem empty_length {α : Type*} {size : ℕ} :
    (EventWindow.empty α size).events.length = 0 := rfl

/-- Pushing into a non-full window keeps every prior event (no eviction;
streaming.rs `EventWindow::push` returns None below capacity). -/
theorem push_not_full {α : Type*} {size : ℕ} {w : EventWindow α size} {e : α}
    (h : w.events.length < size) : (w.push e).events = e :: w.events := by
  simp only [EventWindow.push]
  rw [List.take_of_length_le]
  simp only [List.length_cons]
  omega

/-- Analysis context (streaming.rs `OnlineMonitoringContext` / `OfflineAnalysisContext`). -/
inductive AnalysisContext where
  | online
  | offline
deriving DecidableEq, Repr


end ProcInt
