-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib

/-! # ProcInt.Analytics.Temporal

Temporal ordering law for process events: TemporalOrder relation, timed events over natural-number ticks, sojourn times as truncated Nat differences, happens-before as a strict order, and temporal profiles. Ported from wasm4pm-compat temporal.rs. Canon: Adriansyah, Munoz-Gama, Carmona, van Dongen, van der Aalst 2015 (temporal profile conformance); van der Aalst 2013 Process Cubes (time as first-class axis). -/

namespace ProcInt

/-- Temporal ordering relation between two events (temporal.rs `TemporalOrder`):
before, after, concurrent (no strict order), unknown. Canon: Adriansyah et al. 2015
temporal profile conformance; van der Aalst 2013 Process Cubes (time as cube axis). -/
inductive TemporalOrder where
  | before
  | after
  | concurrent
  | unknown
deriving DecidableEq, Repr

/-- An event with an activity label and a natural-number timestamp
(temporal.rs `TimeAwareEvidence` context, discretized to ℕ ticks). -/
structure TimedEvent (α : Type*) where
  activity : α
  timestamp : ℕ

/-- Sojourn time between two events as truncated ℕ difference of timestamps
(temporal.rs `TimeDelta` / `SojournTimeWitness`). -/
def sojourn {α : Type*} (a b : TimedEvent α) : ℕ :=
  b.timestamp - a.timestamp

/-- Happens-before as a strict order on timestamps (temporal.rs `TemporalOrder::Before`). -/
def HappensBefore {α : Type*} (a b : TimedEvent α) : Prop :=
  a.timestamp < b.timestamp

/-- Temporal profile for an activity pair: average and standard deviation of the
inter-activity delay, as ℚ (temporal.rs `TemporalProfile`). -/
structure TemporalProfile (α : Type*) where
  pair : α × α
  avg : ℚ
  std : ℚ

/-- Happens-before is irreflexive: no event strictly precedes itself
(temporal.rs `TemporalOrder::Before` is strict; from Nat.lt). -/
theorem happensBefore_irrefl {α : Type*} (e : TimedEvent α) : ¬ HappensBefore e e :=
  Nat.lt_irrefl e.timestamp

/-- Happens-before is transitive (strict-order law of temporal.rs `TemporalOrder`). -/
theorem happensBefore_trans {α : Type*} {a b c : TimedEvent α}
    (hab : HappensBefore a b) (hbc : HappensBefore b c) : HappensBefore a c :=
  Nat.lt_trans hab hbc

/-- The sojourn time of an event relative to itself is zero (temporal.rs `TimeDelta`). -/
theorem sojourn_self {α : Type*} (e : TimedEvent α) : sojourn e e = 0 :=
  Nat.sub_self e.timestamp


end ProcInt
