#!/usr/bin/env python3
"""Emit .mfact/artifacts.toml — the artifact ledger.

There are no generated files; there are only artifacts with receipts.
Generation is not a location, it is a provenance relation: this ledger is
what confers authority, not paths and not file headers. Entries for
ggen-rendered artifacts come from the live ggen receipt
(.ggen-v2/receipt.json outputs map); builder-emitted artifacts are declared
explicitly with their sources."""
import json, os, subprocess

ROOT = os.environ.get('MFACT_ROOT',
                      os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
receipt = json.load(open(os.path.join(ROOT, '.ggen-v2/receipt.json')))
payload = receipt.get('payload', receipt)
outputs = payload.get('outputs', {})

PACK_OF = lambda p: ('quadrature-pack' if ('quadrature' in p or p.startswith('paper/') or 'Release/' in p)
                     else 'lean-math-pack')

lines = ['# GENERATED by scripts/build_ledger.py from the ggen receipt chain.',
         '# Authority comes from this ledger, not from paths or headers.', '']
for path in sorted(outputs):
    lines += ['[[artifact]]',
              f'path = "{path}"',
              'producer = "ggen"',
              f'pack = "/Users/sac/mfact/packs/{PACK_OF(path)}"',
              f'content_hash = "blake3:{outputs[path]}"', '']

def b3(path):
    return subprocess.run(['b3sum', '--no-names', os.path.join(ROOT, path)],
                          capture_output=True, check=True).stdout.decode().strip()

for path, producer, sources in [
    ('paper/evaluation.tex', 'scripts (manifest-derived; numbers verified by quadrature eval check)',
     ['release/release-manifest.json']),
    ('release/release-manifest.json', 'scripts/build_manifest.py',
     ['packs/lean-math-pack/ontology.ttl']),
    ('release/gates.json', 'scripts/build_manifest.py',
     ['release/release-manifest.json']),
    ('release/standing.env', 'gates (computed fields; quadrature fields merged from release/quadrature.env)',
     ['release/release-manifest.json', 'release/quadrature.env']),
    ('paper/correspondence_status.tex', 'scripts/build_verif.py',
     ['packs/lean-math-pack/fragments/verif.ttl', 'release/verif-receipt.json']),
    ('release/verif-receipt.json', 'scripts/build_verif.py',
     ['packs/lean-math-pack/fragments/verif.ttl']),
    ('release/replay_report.json', 'scripts/independent_replay.sh',
     ['release/release-manifest.json']),
    ('release/docs_report.json', 'scripts/build_docs.sh',
     ['release/release-manifest.json']),
    ('rslab/receipts/praxis_graphlaw_benchmark_receipt.toml', 'rslab/scripts/collect_praxis_graphlaw.py',
     ['rslab/experiments/praxis_graphlaw/raw/bench_graphlaw.txt',
      'rslab/experiments/praxis_graphlaw/raw/bench_root.txt',
      'rslab/experiments/praxis_graphlaw/raw/test_graphlaw.txt',
      'rslab/experiments/praxis_graphlaw/raw/test_e2e.txt',
      'rslab/experiments/praxis_graphlaw/raw/toolchain_context.txt',
      'rslab/experiments/praxis_graphlaw/raw/command_log.txt',
      'rslab/experiments/praxis_graphlaw/experiment_meta.toml',
      'rslab/schemas/benchmark_result.schema.json']),
    ('rslab/paper_fragments/praxis_graphlaw_evidence.tex', 'rslab/scripts/render_paper_fragments.py',
     ['rslab/receipts/praxis_graphlaw_benchmark_receipt.toml']),
]:
    lines += ['[[artifact]]', f'path = "{path}"', f'producer = "{producer}"',
              f'sources = {json.dumps(sources)}',
              f'content_hash = "blake3:{b3(path)}"', '']

os.makedirs(os.path.join(ROOT, '.mfact'), exist_ok=True)
out = os.path.join(ROOT, '.mfact/artifacts.toml')
open(out, 'w').write('\n'.join(lines))
print(f'{out}: {sum(1 for l in lines if l == "[[artifact]]")} artifacts ledgered')
