#!/usr/bin/env python3
"""export_lexicon.py -- deterministic projection of MFW Notation Authority tags.

Renders docs/LEXICON.md from the [Notation Authority §N]-tagged declarations
in procint/ProcInt/MFW/*.lean.

Inputs (read-only):
  - procint/ProcInt/MFW/*.lean  (non-recursive; Tests/ subdirectory excluded)
  - git HEAD of the repository  (via `git rev-parse HEAD`)

Outputs:
  - docs/LEXICON.md  (overwritten in full on every run)

Mutation boundary:
  Writes exactly one file, docs/LEXICON.md. Reads Lean sources and git
  metadata. Runs no build, no lint, no network. Touches nothing else.

Determinism:
  Same tree -> same bytes. Entries are ordered by (section number, file name,
  line number). The only tree-dependent data are the extracted declarations,
  the per-file SHA-256 digests, and the git HEAD hash. No timestamps.

Usage:
  python3 scripts/export_lexicon.py        # from the repository root
"""

import hashlib
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MFW_DIR = REPO_ROOT / "procint" / "ProcInt" / "MFW"
OUT_PATH = REPO_ROOT / "docs" / "LEXICON.md"

TAG_RE = re.compile(r"\[Notation Authority §(\d+)\]")
NAME_RE = re.compile(
    r"^\s*(?:@\[[^\]]*\]\s*)?(?:protected\s+|private\s+)?(?:noncomputable\s+)?"
    r"(def|theorem|structure|inductive|abbrev|class|instance|opaque)\s+"
    r"([A-Za-z0-9_.'₀-₉!?]+)"
)
SIG_MAX_LINES = 6


def decl_name(sig_lines):
    """Best-effort declaration (or field) name from the signature lines."""
    for line in sig_lines:
        m = NAME_RE.match(line)
        if m:
            return m.group(2)
    # Structure field: `name : Type` (possibly indented).
    first = sig_lines[0].strip() if sig_lines else ""
    if ":" in first:
        head = first.split(":", 1)[0].strip()
        if head and re.fullmatch(r"[A-Za-z0-9_.'₀-₉!?]+", head):
            return head + " (field)"
    return "(unnamed)"


def wrap_line(line, width=100):
    """Deterministically soft-wrap a prose line at the last space <= width."""
    out = []
    while len(line) > width:
        cut = line.rfind(" ", 0, width + 1)
        if cut <= 0:
            break
        out.append(line[:cut])
        line = line[cut + 1:]
    out.append(line)
    return "\n".join(out)


def wrap_prose(text, width=100):
    return "\n".join(wrap_line(l, width) for l in text.splitlines())


def sig_done(line):
    """Signature-capture stop condition: the declaration head has ended."""
    stripped = line.rstrip()
    return (
        ":=" in stripped
        or stripped.endswith(" where")
        or stripped.endswith("where")
        or stripped.endswith(" by")
    )


def extract_entries(path):
    """Yield (section, file, doc_line, docstring, sig_lines) for tagged decls."""
    lines = path.read_text(encoding="utf-8").splitlines()
    i = 0
    n = len(lines)
    while i < n:
        stripped = lines[i].lstrip()
        if not stripped.startswith("/--"):
            i += 1
            continue
        doc_start = i
        doc_lines = []
        while i < n:
            doc_lines.append(lines[i])
            if "-/" in lines[i]:
                break
            i += 1
        i += 1
        doc_text = "\n".join(doc_lines)
        m = TAG_RE.search(doc_text)
        if not m:
            continue
        section = int(m.group(1))
        # Clean docstring: strip the /-- and -/ delimiters, keep interior text.
        body = doc_text
        body = re.sub(r"^\s*/--\s?", "", body)
        body = re.sub(r"\s*-/\s*$", "", body)
        # Capture the declaration signature immediately after the doc comment.
        sig = []
        j = i
        while j < n and len(sig) < SIG_MAX_LINES:
            nxt = lines[j]
            ns = nxt.strip()
            if ns == "" or ns.startswith("/--") or ns.startswith("/-!"):
                break
            sig.append(nxt.rstrip())
            if sig_done(nxt):
                break
            j += 1
        if not sig:
            continue
        yield section, path.name, doc_start + 1, body, sig


HEADER = """# MFW Lexicon

Generated by `scripts/export_lexicon.py`. Do not edit by hand; regenerate with
`python3 scripts/export_lexicon.py` from the repository root.

## Purpose

This file is a decoder-initialization preamble. A language model reading this
repository arrives with corpus priors -- the meanings a term carries in the
general AI/software-engineering corpus -- and those priors diverge from the
denotations this repository has fixed formally. This lexicon pins repo
denotations against those priors before any MFW source is interpreted.

Which terms need full entries was ranked by cold-read probes run this session
(2026-07-16): context-free agents were asked what each term means in the
general corpus, and the answers were diffed against the repo's formal
anchors. The rankings are qualitative and UNVERIFIED as measurements; they
order editorial attention, they do not create standing. High-divergence terms
("post-AGI"-class: terms whose corpus reading actively contradicts or misses
the repo denotation) get full divergence rows and formal anchors below.
Low-divergence terms get spot references only.

## Trust Chain

Four edges, each weaker than the last. Stated honestly:

1. **Lean source -> kernel: entailment.** Tagged declarations below live in
   compiled Lean. Proof-carrying ones are kernel-checked; `def : Prop` shapes
   are statements, not results. Receipt for the verified base:
   `.verif-toolchain/receipts/receipt-20260716T223859Z.txt` (build exit 0,
   lint exit 0) at git HEAD f6958bbfcfd.
2. **Projection -> digest: identity.** This file is bound to its sources by
   the SHA-256 digests and git HEAD in the Provenance section. Same tree,
   same bytes. The digest proves identity of projection, not truth of content.
3. **Context residency -> capacity.** An entry only helps a decoder while it
   is resident in that decoder's context window. Nothing here guarantees
   residency; capacity is a budget, not a property of this file.
4. **Decode: UNVERIFIED.** Initialization is not compliance. A reader that
   has seen this file can still decode "kernel" as an OS kernel. What the
   lexicon changes is the status of such misreadings: they become citable
   contradictions against a pinned anchor (§N, file:line), not
   impossibilities.

## Re-Anchoring Convention

Cite a term's §N inline at each use site: "the fiber entropy [§42] of this
class", "receipted [§4] actuation". A use site without an inline anchor is
re-derivable from this file but not pinned; anchored uses survive context
truncation better because the anchor travels with the sentence.

## Divergence Table

Corpus cold-read = what the context-free probe returned (one clause). Repo
denotation = what this repository means, with the formal anchor where one
exists. Rows without formal anchors say so; do not invent anchors for them.

| Term | Corpus cold-read | Repo denotation | Div. |
| --- | --- | --- | --- |
| post-AGI | era after human-level general AI | unformalized; no anchor (see notes) | high |
| multifractal workflow | no fixed meaning | spectrum bundle; §166 SpectrumBundle.lean:101 | high |
| attention capacity | context-window limit | no formal decl (see notes) | high |
| admitted observation | trusted without proof | admitted input; §1 Manufacture.lean:13 | med |
| standing | legal / persistent | fixed status grammar; §3 Manufacture.lean:19 | high |
| receipt | evidence an event occurred | same sense, formal relation; §4 Manufacture.lean:21 | low |
| manufacture | pejorative: fabricate | lawful production law; §2 Manufacture.lean:17 | high |
| kernel | OS / GPU compute kernel | equivalence kernel of tau; §69 Kernel.lean:296 | high |
| fiber entropy | ergodic-theory notion | log fiber cardinality; §42 FiberEntropy.lean:147 | med |
| trace equivalence | same action sequences | Mazurkiewicz; §68 Kernel.lean:222 | low |

Notes on the terse rows above:

- `post-AGI`: unformalized. `GapCalculus.lean` exists at generation time
  (Little's-law identities, USL/PK formulas, diagonal conjectures) but defines
  no post-AGI notion; the term appears only in informal prose. No anchor.
- `attention capacity`: no formal declaration exists; the nearest repo usages
  are the informal reading of the Renyi exponent `q` as an attention control
  (SpectrumBundle.lean:66 and :331) and the capacity-shaped formulas
  `coherenceHorizon` and `throughputCeiling` in `GapCalculus.lean`. None of
  these is declared to denote "attention capacity"; equating them here would
  manufacture an anchor.
- `standing`: the value grammar is fixed by the root `AGENTS.md` Standing Law
  and `procint/AGENTS.md` (declaration-level CONJECTURAL / PROVEN tags); the
  formal artifact-standing predicate is `stand` [§3].
- `manufacture`: the repo deliberately uses the industrial sense -- repeatable
  production of artifacts from admitted observations under a stated law --
  never the "fabricate evidence" sense the corpus defaults to.
- `fiber entropy`: same spirit as the ergodic-theory notion (uncertainty
  remaining within tau-preimages), realized as `log |F_w|` in a finite
  uniform model, not as measure-theoretic conditional entropy.

"""

SEE_ALSO = """## See Also

- `../AGENTS.md` -- repository Standing Law; the vocabulary this lexicon pins
- `../procint/AGENTS.md` -- procint standing grammar (CONJECTURAL / PROVEN tags)
- `../procint/ProcInt/MFW/AUDIT_FOLLOWUP.md` -- audit of unproven theorem-shaped
  declarations behind several entries above
- `../scripts/README.md` -- entry for `export_lexicon.py`, the generator of this file
"""


def main():
    if not MFW_DIR.is_dir():
        print(f"error: {MFW_DIR} not found", file=sys.stderr)
        return 1
    files = sorted(p for p in MFW_DIR.glob("*.lean"))
    entries = []
    for path in files:
        entries.extend(extract_entries(path))
    entries.sort(key=lambda e: (e[0], e[1], e[2]))

    head = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "rev-parse", "HEAD"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()

    out = [HEADER]
    out.append("## Lexicon Entries\n\n")
    out.append(
        "Each entry: tag section number, declaration, source location, the\n"
        "source docstring, and the declaration head as it appears in Lean.\n\n"
    )
    for section, fname, line, doc, sig in entries:
        name = decl_name(sig)
        out.append(f"### §{section} `{name}` -- {fname}:{line}\n\n")
        out.append(wrap_prose(doc.strip()) + "\n\n")
        out.append("```lean\n" + "\n".join(sig) + "\n```\n\n")

    out.append("## Provenance\n\n")
    out.append(
        "This projection is digest-bound to its sources. Recompute with\n"
        "`shasum -a 256` over each file below; any mismatch means this file\n"
        "no longer describes the tree it claims to describe.\n\n"
    )
    out.append(f"Git HEAD at generation: `{head}`\n\n")
    for path in files:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        rel = path.relative_to(REPO_ROOT)
        out.append(f"- `{rel}`\n  `sha256:{digest}`\n")
    out.append("\n")
    out.append(SEE_ALSO)

    text = "".join(out)
    OUT_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {OUT_PATH} ({len(entries)} entries from {len(files)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
