#!/usr/bin/env python3
"""Compute TYPE_INVENTORY_HASH: the only code in this repo that produces it.

Closes GAP_LEDGER_v26.7.12.md G9 — the value used to be hand-injected into
release/standing.env with a provenance file (release/type_inventory_provenance.txt)
that documented a *different*, equally unreproducible hash. Neither prior value
could be regenerated by any script anywhere in the tree.

Definition (constructive, reproducible by anyone with git access to the pinned
commit): TYPE_INVENTORY_HASH = blake3(manifest), where `manifest` is the
newline-joined, path-sorted list of "<path> <git-blob-sha1>" pairs for every
`*.rs` file tracked under `src/` in SOURCE_REPO at SOURCE_COMMIT (git blob
hashes via `git ls-tree`, not working-tree content — the source repo may be
dirty locally, but its git history at the pinned commit is immutable).

Also upserts release/standing.env's line-1 header comment (G6 hygiene prep,
TAG_DECISION_BRIEF_v26.7.13.md): the header used to hand-carry a release
string ("v26.7.6") that drifted from the actual release the moment
build_manifest.py's RELEASE constant moved on without it. The header is now
derived from release/release-manifest.json's own "release" field — the same
manifest build_manifest.py writes immediately before invoking this generator
(see build_manifest.py's call site) — so there is exactly one place a release
identifier is asserted from, and standing.env's header can only ever agree
with it or fail loudly.

Usage:
    python3 scripts/gen_type_inventory_hash.py

Writes release/type_inventory_provenance.txt and upserts TYPE_INVENTORY_HASH=
and the line-1 header in release/standing.env. Invoked from
scripts/build_manifest.py so `just regen-check` / `just build-manifest` keep
all three in lockstep with the pinned source commit and the current release.
Never hand-edit any output file.
"""
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Pinned per the pre-existing (now-superseded) provenance claim; unchanged by
# this fix — only the derivation is now real. Re-pin here (and only here) if
# the release ever tracks a newer wasm4pm-compat commit.
SOURCE_REPO = '/Users/sac/wasm4pm-compat'
SOURCE_COMMIT = '6aead3c'

STANDING_ENV = os.path.join(ROOT, 'release/standing.env')
PROVENANCE = os.path.join(ROOT, 'release/type_inventory_provenance.txt')
RELEASE_MANIFEST = os.path.join(ROOT, 'release/release-manifest.json')


def b3(data: bytes) -> str:
    return subprocess.run(['b3sum', '--no-names'], input=data,
                           capture_output=True, check=True).stdout.decode().strip()


def type_surface_blobs():
    """(path, blob_sha1) for every *.rs file under src/ at SOURCE_COMMIT,
    sorted by path — the crate's tracked type surface, read via git blob
    objects so a dirty SOURCE_REPO working tree cannot perturb the hash."""
    if not os.path.isdir(os.path.join(SOURCE_REPO, '.git')):
        raise SystemExit(
            f'REFUSED: SOURCE_REPO {SOURCE_REPO} not present or not a git '
            'checkout — cannot compute TYPE_INVENTORY_HASH from a claim, '
            'only from the pinned commit\'s actual blobs.')
    out = subprocess.run(
        ['git', '-C', SOURCE_REPO, 'ls-tree', '-r', SOURCE_COMMIT, '--', 'src/'],
        capture_output=True, check=True).stdout.decode()
    blobs = []
    for line in out.splitlines():
        # "<mode> blob <sha1>\t<path>"
        meta, path = line.split('\t', 1)
        if not path.endswith('.rs'):
            continue
        sha1 = meta.split()[2]
        blobs.append((path, sha1))
    if not blobs:
        raise SystemExit(
            f'REFUSED: no *.rs blobs found under src/ at {SOURCE_REPO}@{SOURCE_COMMIT}')
    return sorted(blobs)


def compute():
    blobs = type_surface_blobs()
    manifest = ''.join(f'{path} {sha1}\n' for path, sha1 in blobs)
    return b3(manifest.encode()), len(blobs), manifest


def write_provenance(digest: str, count: int) -> None:
    with open(PROVENANCE, 'w') as f:
        f.write(f'TYPE_INVENTORY_HASH={digest}\n')
        f.write(f'SOURCE_REPO={SOURCE_REPO}\n')
        f.write(f'SOURCE_COMMIT={SOURCE_COMMIT}\n')
        f.write(f'SOURCE_FILE_COUNT={count}\n')
        f.write(
            'NOTE=hash is blake3(manifest); manifest is the path-sorted '
            '"<path> <git-blob-sha1>\\n" lines for every *.rs file under src/ '
            'at SOURCE_COMMIT, read via `git ls-tree` (immutable blobs, not '
            'working tree). Regenerate via scripts/gen_type_inventory_hash.py '
            '— this file and release/standing.env TYPE_INVENTORY_HASH must '
            'always agree; disagreement is GAP G9.\n')


def read_release() -> str:
    """The single source of truth for the release identifier: release/release-manifest.json's
    own "release" field. build_manifest.py writes that manifest, then invokes this generator
    (see build_manifest.py's call site) — so by the time this runs, the manifest already
    carries the current release. Never hand-carry a version string here or anywhere else that
    can independently drift."""
    if not os.path.exists(RELEASE_MANIFEST):
        raise SystemExit(
            f'REFUSED: {RELEASE_MANIFEST} does not exist — run scripts/build_manifest.py '
            'first (it writes release-manifest.json before invoking this generator).')
    with open(RELEASE_MANIFEST) as f:
        manifest = json.load(f)
    release = manifest.get('release')
    if not release:
        raise SystemExit(f'REFUSED: {RELEASE_MANIFEST} has no "release" field')
    return release


def upsert_header(release: str) -> None:
    """Upsert release/standing.env's line-1 header comment so it always names the manifest's
    own release identifier, never a hand-carried string that can drift (G6 hygiene prep,
    TAG_DECISION_BRIEF_v26.7.13.md: the header previously said "v26.7.6" while the manifest
    had already moved to v26.7.7, with nothing regenerating the comment)."""
    header = (f'# mfact/procint release {release} — standing report '
              '(machine-checkable, computed not asserted)\n')
    if not os.path.exists(STANDING_ENV):
        raise SystemExit(f'REFUSED: {STANDING_ENV} does not exist')
    with open(STANDING_ENV) as f:
        lines = f.readlines()
    if lines and lines[0].startswith('# mfact/procint release '):
        lines[0] = header
    else:
        lines.insert(0, header)
    with open(STANDING_ENV, 'w') as f:
        f.writelines(lines)


def upsert_standing_env(digest: str) -> None:
    key = 'TYPE_INVENTORY_HASH='
    if not os.path.exists(STANDING_ENV):
        raise SystemExit(f'REFUSED: {STANDING_ENV} does not exist')
    with open(STANDING_ENV) as f:
        lines = f.readlines()
    found = False
    for i, line in enumerate(lines):
        if line.startswith(key):
            lines[i] = f'{key}{digest}\n'
            found = True
            break
    if not found:
        lines.append(f'{key}{digest}\n')
    with open(STANDING_ENV, 'w') as f:
        f.writelines(lines)


def main() -> int:
    release = read_release()
    upsert_header(release)
    digest, count, _manifest = compute()
    write_provenance(digest, count)
    upsert_standing_env(digest)
    print(f'TYPE_INVENTORY_HASH={digest} SOURCE_FILE_COUNT={count} '
          f'(src={SOURCE_REPO}@{SOURCE_COMMIT}) release={release}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
