-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
import ProcInt

/-! # Axiom audit — procint package

Machine-checked evidence that every declaration recorded as `proven` in the
procint ontology rests only on the trusted axiom set
`[propext, Classical.choice, Quot.sound]` and carries no transitive
`sorryAx`. The build breaks on any drift between ontology and kernel. -/


