-- GENERATED by `ggen sync` from lean-math-pack (procint ontology).
-- Do not edit by hand: candidates enter through the ontology, never here.
import Mathlib
import ProcInt.Petri.Net

/-! # ProcInt.Workflow.Flow

The flow relation of a Petri net as a directed graph on the disjoint union of places and transitions, with its bipartiteness lemmas. This is the relation F of van der Aalst 1997 (Verification of Workflow Nets, Definition 6), the substrate for the path condition of workflow nets. -/

namespace ProcInt

/-- The flow relation of a Petri net viewed as a directed graph on `P ⊕ T`.
There is an edge from place `p` to transition `t` iff `p` is an input place of
`t` (positive pre-weight), and from `t` to `p` iff `p` is an output place of
`t` (positive post-weight). Places never connect to places, transitions never
to transitions (bipartiteness). This is the flow relation `F` of
van der Aalst 1997, Verification of Workflow Nets, Definition 6. -/
def PetriNet.FlowEdge {P T : Type} (N : PetriNet P T) : (P ⊕ T) → (P ⊕ T) → Prop :=
  fun x y => match x, y with
  | .inl p, .inr t => 0 < N.pre t p
  | .inr t, .inl p => 0 < N.post t p
  | _, _ => False

/-- A place-to-transition flow edge is exactly a positive pre-weight
(van der Aalst 1997, Def 6: `(p, t) ∈ F ↔ p ∈ •t`). -/
theorem PetriNet.flowEdge_inl_inr {P T : Type} (N : PetriNet P T) (p : P) (t : T) :
    N.FlowEdge (Sum.inl p) (Sum.inr t) ↔ 0 < N.pre t p := Iff.rfl

/-- A transition-to-place flow edge is exactly a positive post-weight
(van der Aalst 1997, Def 6: `(t, p) ∈ F ↔ p ∈ t•`). -/
theorem PetriNet.flowEdge_inr_inl {P T : Type} (N : PetriNet P T) (t : T) (p : P) :
    N.FlowEdge (Sum.inr t) (Sum.inl p) ↔ 0 < N.post t p := Iff.rfl

/-- Bipartiteness of the flow relation, place side: no flow edge connects two
places (Murata 1989 §II; van der Aalst 1997, Def 6). -/
theorem PetriNet.not_flowEdge_inl_inl {P T : Type} (N : PetriNet P T) (p q : P) :
    ¬ N.FlowEdge (Sum.inl p) (Sum.inl q) := fun h => h

/-- Bipartiteness of the flow relation, transition side: no flow edge connects
two transitions (Murata 1989 §II; van der Aalst 1997, Def 6). -/
theorem PetriNet.not_flowEdge_inr_inr {P T : Type} (N : PetriNet P T) (t u : T) :
    ¬ N.FlowEdge (Sum.inr t) (Sum.inr u) := fun h => h

/-- The flow relation is irreflexive: bipartiteness forbids self-loops on a
single node of `P ⊕ T` (a self-loop `p → t → p` is two distinct edges). -/
theorem PetriNet.flowEdge_irrefl {P T : Type} (N : PetriNet P T) :
    ∀ x : P ⊕ T, ¬ N.FlowEdge x x := fun x =>
  match x with
  | .inl _ => fun h => h
  | .inr _ => fun h => h


end ProcInt
