-- Hand-authored. Not rendered by ggen. Not ledgered in .mfact/artifacts.toml.
-- Edits here are ordinary code review, not artifact drift.
/-!
# Causal Replay and Independent-Step Confluence

Pipeline:
`deterministic local transition → event trace → adjacent commuting swaps → trace equivalence`.

Crown law:
traces related by a finite closure of admitted commuting swaps replay to the same consequence.

Preserves:
initial state and deterministic transition function.

Excludes:
global total order and hidden external state.

Falsifier:
an admitted commuting swap changes replay consequence.
-/

namespace ProcInt.Playground.Swarm11

namespace Replay

/-- Deterministic replay of an event list. -/
def replay {Event State : Type}
    (step : Event → State → State) :
    List Event → State → State
  | [], state => state
  | event :: rest, state => replay step rest (step event state)

/-- Two events commute when either execution order has the same consequence in every state. -/
def Commute {Event State : Type}
    (step : Event → State → State)
    (left right : Event) : Prop :=
  ∀ state, step right (step left state) = step left (step right state)

/-- Replay distributes across trace concatenation. -/
theorem replay_append {Event State : Type}
    (step : Event → State → State)
    (leading suffix : List Event)
    (state : State) :
    replay step (leading ++ suffix) state =
      replay step suffix (replay step leading state) := by
  induction leading generalizing state with
  | nil => rfl
  | cons event rest inductionHypothesis =>
      simp [replay, inductionHypothesis]

/--
One admitted adjacent commuting swap preserves replay consequence.

Law:
`a I b → replay(leading·a·b·suffix) = replay(leading·b·a·suffix)`.
Carrier: deterministic event traces.
Admission: `Commute step left right`.
Preserves: initial and final state.
Refuses: commutation without a proof.
Claim ceiling: theorem.
-/
theorem replay_adjacent_swap_of_commute
    {Event State : Type}
    (step : Event → State → State)
    (leading suffix : List Event)
    (left right : Event)
    (state : State)
    (hCommute : Commute step left right) :
    replay step (leading ++ left :: right :: suffix) state =
      replay step (leading ++ right :: left :: suffix) state := by
  rw [replay_append, replay_append]
  change
    replay step suffix (step right (step left (replay step leading state))) =
      replay step suffix (step left (step right (replay step leading state)))
  rw [hCommute]

/--
Trace equivalence generated by adjacent swaps of admitted commuting events.
-/
inductive TraceEq {Event State : Type}
    (step : Event → State → State) :
    List Event → List Event → Prop where
  | refl (trace : List Event) :
      TraceEq step trace trace
  | swap
      (leading suffix : List Event)
      (left right : Event)
      (hCommute : Commute step left right) :
      TraceEq step
        (leading ++ left :: right :: suffix)
        (leading ++ right :: left :: suffix)
  | symm {left right : List Event} :
      TraceEq step left right →
      TraceEq step right left
  | trans {left middle right : List Event} :
      TraceEq step left middle →
      TraceEq step middle right →
      TraceEq step left right

/--
All traces in the admitted commuting-swap equivalence class have identical replay consequence.

This is the canonical consequence theorem for the finite trace relation used here.
-/
theorem replay_eq_of_traceEq
    {Event State : Type}
    (step : Event → State → State)
    {left right : List Event}
    (equivalent : TraceEq step left right)
    (state : State) :
    replay step left state = replay step right state := by
  induction equivalent with
  | refl trace => rfl
  | swap leading suffix first second hCommute =>
      exact replay_adjacent_swap_of_commute
        step leading suffix first second state hCommute
  | symm relation inductionHypothesis =>
      exact inductionHypothesis.symm
  | trans firstRelation secondRelation firstIH secondIH =>
      exact firstIH.trans secondIH

/--
Exact replay receipt.

The record is mathematical consequence binding, not a cryptographic authenticity claim.
-/
structure Receipt (Event State : Type) where
  initial : State
  trace : List Event
  final : State
  deriving Repr

/-- Manufactures a receipt by executing the deterministic transition function. -/
def manufactureReceipt {Event State : Type}
    (step : Event → State → State)
    (initial : State)
    (trace : List Event) : Receipt Event State where
  initial := initial
  trace := trace
  final := replay step trace initial

/-- Propositional validity of an exact replay receipt. -/
def ValidReceipt {Event State : Type}
    (step : Event → State → State)
    (receipt : Receipt Event State) : Prop :=
  replay step receipt.trace receipt.initial = receipt.final

/-- Every manufactured receipt is valid by construction. -/
theorem manufacturedReceipt_valid
    {Event State : Type}
    (step : Event → State → State)
    (initial : State)
    (trace : List Event) :
    ValidReceipt step (manufactureReceipt step initial trace) := by
  rfl

/-- Trace-equivalent manufactured receipts bind the same final consequence. -/
theorem equivalentTraces_sameFinal
    {Event State : Type}
    (step : Event → State → State)
    {left right : List Event}
    (equivalent : TraceEq step left right)
    (initial : State) :
    (manufactureReceipt step initial left).final =
      (manufactureReceipt step initial right).final := by
  exact replay_eq_of_traceEq step equivalent initial

end Replay

end ProcInt.Playground.Swarm11
